// soc-net-react/src/routes/profile.js
import { useContext, useEffect, useState } from "react";
import { AppContext } from "../contexts/contexts";
import { useNavigate } from "react-router-dom";
import { removeUserById, updateUser } from "../api/userService";
import './profile.css'

export default function Profile() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const [firstName, setFirstName] = useState(appContext.user.firstName);
    const [lastName, setLastName] = useState(appContext.user.lastName);
    const [birthDate, setBirthDate] = useState(appContext.user.birthDate);

    useEffect(() => {
        setFirstName(appContext.user.firstName);
        setLastName(appContext.user.lastName);
        setBirthDate(appContext.user.birthDate);
    }, [])

    return (
        <section
            className="profile-container"
        >
            <div
                className="profile-card"
            >
                <input
                    placeholder='Имя'
                    value={firstName}
                    onChange={e => setFirstName(e.target.value)}
                />
                <input
                    placeholder='Фамилия'
                    value={lastName}
                    onChange={e => setLastName(e.target.value)}
                />
                <input
                    type='date'
                    value={birthDate}
                    onChange={e => setBirthDate(e.target.value)}
                />
                <button
                    className="background-color-green"
                    onClick={updateUserButtonOnClick}
                >
                    Редактировать
                </button>
                <button
                    className="background-color-gray"
                    onClick={logoutButtonOnClick}
                >
                    Выйти
                </button>
                <button
                    className="background-color-red"
                    onClick={removeUserButtonOnClick}
                >
                    Удалить аккаунт
                </button>
            </div>
        </section>
    );

    async function updateUserButtonOnClick() {
        await updateUser(appContext.user.id, firstName, lastName, birthDate, appContext.user.image);
        const user = JSON.parse(JSON.stringify(appContext.user));
        user.firstName = firstName;
        user.lastName = lastName;
        user.birthDate = birthDate;
        appContext.setUser(user);
    }

    function logoutButtonOnClick() {
        appContext.removeCookie('userId');
        appContext.removeCookie('token');
        appContext.setIsAuthenticated(false);
        navigate('/');
    }

    async function removeUserButtonOnClick() {
        await removeUserById(appContext.user.id);
        logoutButtonOnClick();
    }
}

// SocNetAngular/src/app/profile/profile.component.ts
import { Component } from '@angular/core';
import { AuthorizationService } from '../services/authorization.service';
import { FormsModule } from '@angular/forms';
import { UserService } from '../services/user.service';
import User from '../entities/user';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.css'
})
export class ProfileComponent {
  firstName = '';
  lastName = '';
  birthDate = '';
  user = new User;
  
  constructor(private authorizationService: AuthorizationService,
    private userService: UserService) {
    authorizationService.user.subscribe(user => {
      this.user = user;
      this.firstName = user.firstName;
      this.lastName = user.lastName;
      this.birthDate = user.birthDate;
    });
  }

  logOut() {
    this.authorizationService.logOut();
    window.location.href = '/signin';
  }

  async updateUser() {
    await this.userService.updateUser(this.user.id, this.firstName, this.lastName, this.birthDate, this.user.image);
    const user = new User;
    user.id = this.user.id;
    user.firstName = this.firstName;
    user.lastName = this.lastName;
    user.birthDate = this.birthDate;
    user.image = this.user.image;
    this.authorizationService.setUser(user);
    alert('Обновлено')
  }

  async removeUser() {
    await this.userService.removeUserById(this.user.id);
    this.logOut();
  }
}

<section
    class="profile-container"
>
    <div
        class="profile-card"
    >
        <input
            placeholder='Имя'
            [(ngModel)]="firstName"
        />
        <input
            placeholder='Фамилия'
            [(ngModel)]="lastName"
        />
        <input
            type='date'
            [(ngModel)]="birthDate"
        />
        <button
            class="background-color-green"
            (click)="updateUser()"
        >
            Редактировать
        </button>
        <button
            class="background-color-gray"
            (click)="logOut()"
        >
            Выйти
        </button>
        <button
            class="background-color-red"
            (click)="removeUser()"
        >
            Удалить аккаунт
        </button>
    </div>
</section>
