// soc-net-react/src/routes/users.js
import { useEffect, useState } from "react";
import { getUsers } from "../api/userService";
import './users.css'

export default function Users() {
    const [users, setUsers] = useState([]);

    useEffect(() => {
        loadUsers();
    }, [])

    return (
        <section
            className="users-container"
        >
            {users.map(user => (
                <p
                    className="user-p"
                    key={user.id}
                >
                    {user.firstName} {user.lastName}
                </p>
            ))}
        </section>
    );

    async function loadUsers() {
        const users = await getUsers();
        setUsers(users);
    }
}

// SocNetAngular/src/app/users/users.component.ts
import { Component } from '@angular/core';
import { UserService } from '../services/user.service';
import User from '../entities/user';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [],
  templateUrl: './users.component.html',
  styleUrl: './users.component.css'
})
export class UsersComponent {
  users: User[] = [];

  constructor(private userService: UserService) {}

  async ngOnInit(){
    this.users = await this.userService.getUsers();
  }
}

<section
    class="users-container"
>
    @for (user of users; track user.id) {
        <p
            class="user-p"
        >
            {{user.firstName}} {{user.lastName}}
        </p>
    }
</section>
