// soc-net-react/src/routes/chats.js
import { useContext, useEffect, useState } from "react";
import { getChats, addChat } from "../api/chatService";
import { AppContext } from "../contexts/contexts";
import { useNavigate } from "react-router-dom";
import './chats.css';
import ChatCard from "../components/chatCard";

export default function Chats() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const [chats, setChats] = useState([]);
    const [name, setName] = useState('');

    useEffect(() => {
        loadChats();
    }, []);

    return (
        <section
            className="chats-container"
        >
            <div
                className="chats-create-container"
            >
                <input
                    placeholder="Название"
                    onChange={e => setName(e.target.value)}
                />
                <button
                    className="background-color-green"
                    onClick={addChatButtonOnClick}
                >
                    Создать
                </button>
            </div>
            {chats.map(chat => (
                <ChatCard
                    key={chat.id}
                    chat={chat}
                    onClick={() => navigateToChat(chat.id)}
                />
            ))}
        </section>
    );

    async function loadChats() {
        try {
            const chats = await getChats();
            setChats(chats);
        } catch (exception) {
            console.log(exception);
        }
    }

    async function addChatButtonOnClick() {
        await addChat(name, appContext.user.id);
        await loadChats();
    }

    function navigateToChat(chatId) {
        navigate(`/chats/${chatId}`);
    }
}

// SocNetAngular/src/app/chats/chats.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ChatService } from '../services/chat.service';
import User from '../entities/user';
import { AuthorizationService } from '../services/authorization.service';
import Chat from '../entities/chat';
import { ChatCardComponent } from '../chat-card/chat-card.component';
import { Router } from '@angular/router';

@Component({
  selector: 'app-chats',
  standalone: true,
  imports: [FormsModule, ChatCardComponent],
  templateUrl: './chats.component.html',
  styleUrl: './chats.component.css'
})
export class ChatsComponent {
  name = '';
  user = new User;
  chats: Chat[] = [];
  
  constructor(private chatService: ChatService,
    authorizationService: AuthorizationService,
    private router: Router) {
    authorizationService.user.subscribe(user => this.user = user);
  }

  async ngOnInit(){
    this.chats = await this.chatService.getChats();
  }

  async addChat() {
    await this.chatService.addChat(this.name, this.user.id);
    this.ngOnInit();
  }

  navigateToChat(chatId: string) {
    this.router.navigate([`/chats/${chatId}`]);
  }
}

<section
    class="chats-container"
>
    <div
        class="chats-create-container"
    >
        <input
            placeholder="Название"
            [(ngModel)]="name"
        />
        <button
            class="background-color-green"
            (click)="addChat()"
        >
            Создать
        </button>
    </div>
    @for (chat of chats; track chat.id) {
        <app-chat-card
            [chat]="chat"
            (click)="navigateToChat(chat.id)"
        >
        </app-chat-card>
    }
</section>
