// SocNetAngular/src/app/chat/chat.component.ts
import { Component } from '@angular/core';
import { ChatService } from '../services/chat.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import Chat from '../entities/chat';
import User from '../entities/user';
import { UserService } from '../services/user.service';
import Message from '../entities/message';
import { MessageService } from '../services/message.service';
import { MessageComponent } from '../message/message.component';
import { AuthorizationService } from '../services/authorization.service';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [FormsModule, MessageComponent],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.css'
})
export class ChatComponent {
  chat = new Chat;
  users: User[] = [];
  chatUsers: User[] = [];
  messages: Message[] = [];
  text = '';
  user = new User;
  
  constructor(private chatService: ChatService,
    private userService: UserService,
    private messageService: MessageService,
    private router: Router,
    authorizationService: AuthorizationService) {
      authorizationService.user.subscribe(user => this.user = user);
    }

  async ngOnInit() {
    await this.loadChat();
    await this.loadUsers();
    await this.loadChatUsers();
    await this.loadMessages();
  }

  async updateChat() {
    await this.chatService.updateChat(this.chat.id, this.chat.name);
    alert('Обновлено');
  }

  async removeChat() {
    await this.chatService.removeChatById(this.chat.id);
    this.router.navigate(['/chats']);
  }

  async loadChat() {
    const parts = this.router.url.split('/');
    this.chat = await this.chatService.getChatById(parts[parts.length - 1]);
  }

  async loadUsers() {
    this.users = await this.userService.getUsersByChatId(this.chat.id, false);
  }

  async loadChatUsers() {
    this.chatUsers = await this.userService.getUsersByChatId(this.chat.id, true);
  }

  async addUserToChat(chatId: string, userId: string) {
    await this.chatService.addUserToChat(chatId, userId);
    this.ngOnInit();
  }

  async removeUserFromChat(chatId: string, userId: string) {
    await this.chatService.removeUserFromChat(chatId, userId);
    this.ngOnInit();
  }

  async loadMessages() {
    this.messages = await this.messageService.getMessagesByChatId(this.chat.id);
  }

  async addMessage() {
    await this.messageService.addMessage(this.chat.id, this.user.id, this.text);
    this.ngOnInit();
  }

  async updateMessage(messageId: string) {
    await this.messageService.updateMessage(messageId, this.text);
    this.ngOnInit();
  }

  async removeMessage(messageId: string) {
    await this.messageService.removeMessageById(messageId);
    this.ngOnInit();
  }
}

<section
    class="chat-container"
>
    <div
        class="chat-subcontainer"
    >
        <input
            placeholder="Название"
            [(ngModel)]="chat.name"
        />
        <button
            class="background-color-green"
            (click)="updateChat()"
        >
            Изменить
        </button>
        <button
            class="background-color-red"
            (click)="removeChat()"
        >
            Удалить
        </button>
    </div>
    <div
        class="chat-content"
    >
        <div
            class="chat-section quater"
        >
            <!-- {users.map(user => (
                <button
                    class="user-button background-color-green"
                    key={user.id}
                    onClick={() => addUserToChatButtonOnClick(chat.id, user.id)}
                >
                    {user.firstName} {user.lastName}
                </button>
            ))} -->
            @for (user of users; track user.id) {
                <button
                    class="user-button background-color-green"
                    (click)="addUserToChat(chat.id, user.id)"
                >
                    {{user.firstName}} {{user.lastName}}
                </button>
            }
        </div>
        <div
            class="chat-section half"
        >
            <section
                class="messages"
            >
                @for (message of messages; track message.id) {
                    <app-message
                        [message]="message"
                        (updateMessage)="updateMessage(message.id)"
                        (removeMessage)="removeMessage(message.id)"
                    >
                    </app-message>
                }
            </section>
            <input
                placeholder="Введите текст"
                [(ngModel)]="text"
            />
            <button
                class="background-color-green"
                (click)="addMessage()"
            >
                Отправить
            </button>
        </div>
        <div
            class="chat-section quater"
        >
            @for (chatUser of chatUsers; track chatUser.id) {
                <button
                    class="user-button background-color-red"
                    (click)="removeUserFromChat(chat.id, chatUser.id)"
                >
                    {{chatUser.firstName}} {{chatUser.lastName}}
                </button>
            }
        </div>
    </div>
</section>

// soc-net-react/src/routes/chat.js
import { useLoaderData, useNavigate } from "react-router-dom";
import { addUserToChat, getChatById, removeChatById, removeUserFromChat, updateChat } from "../api/chatService";
import { useContext, useEffect, useState } from "react";
import { getUsersByChatId } from "../api/userService";
import { addMessage, getMessagesByChatId, removeMessageById, updateMessage } from "../api/messageService";
import { AppContext } from "../contexts/contexts";
import './chat.css'

export async function chatLoader({ params }) {
    const chat = await getChatById(params.chatId);

    return { chat }
}

export default function Chat() {
    const { chat } = useLoaderData();

    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const [name, setName] = useState(chat.name);
    const [users, setUsers] = useState([]);
    const [chatUsers, setChatUsers] = useState([]);
    const [reload, setReload] = useState(false);

    const [messages, setMessages] = useState([]);
    const [text, setText] = useState('');

    useEffect(() => {
        loadUsers(chat.id);
        loadChatUsers(chat.id);
        loadMessages(chat.id)
    }, [reload]);

    return (
        <section
            className="chat-container"
        >
            <div
                className="chat-subcontainer"
            >
                <input
                    placeholder="Название"
                    value={name}
                    onChange={e => setName(e.target.value)}
                />
                <button
                    className="background-color-green"
                    onClick={updateChatButtonOnClick}
                >
                    Изменить
                </button>
                <button
                    className="background-color-red"
                    onClick={removeChatButtonOnClick}
                >
                    Удалить
                </button>
            </div>
            <div
                className="chat-content"
            >
                <div
                    className="chat-section quater"
                >
                    {users.map(user => (
                        <div key={user.id}>
                            <button
                                className="background-color-green"
                                onClick={() => addUserToChatButtonOnClick(chat.id, user.id)}
                            >
                                {user.firstName} {user.lastName}
                            </button>
                        </div>
                    ))}
                </div>
                <div
                    className="chat-section half"
                >
                    <input
                        placeholder="Введите текст"
                        value={text}
                        onChange={e => setText(e.target.value)}
                        
                    />
                    <button
                        className="background-color-green"
                        onClick={addMessageButtonOnClick}
                    >
                        Отправить
                    </button>
                    {messages.map(message => (
                        <div key={message.id}>
                            {message.text}
                            <button
                                className="background-color-green"
                                onClick={() => updateMessageButtonOnClick(message.id)}
                            >
                                Изменить
                            </button>
                            <button
                                className="background-color-red"
                                onClick={() => removeMessageButtonOnClick(message.id)}
                            >
                                Удалить
                            </button>
                        </div>
                    ))}
                </div>
                <div
                    className="chat-section quater"
                >
                    {chatUsers.map(user => (
                        <div key={user.id}>
                            <button
                                className="background-color-red"
                                onClick={() => removeUserFromChatButtonOnClick(chat.id, user.id)}
                            >
                                {user.firstName} {user.lastName}
                            </button>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );

    async function updateChatButtonOnClick() {
        await updateChat(chat.id, name);
    }

    async function removeChatButtonOnClick() {
        await removeChatById(chat.id);
        navigate('/chats');
    }

    async function loadUsers(chatId) {
        const users = await getUsersByChatId(chatId, false);
        setUsers(users);
    }

    async function loadChatUsers(chatId) {
        const chatUsers = await getUsersByChatId(chatId, true);
        setChatUsers(chatUsers);
    }

    async function addUserToChatButtonOnClick(chatId, userId) {
        await addUserToChat(chatId, userId);
        setReload(!reload);
    }

    async function removeUserFromChatButtonOnClick(chatId, userId) {
        await removeUserFromChat(chatId, userId);
        setReload(!reload);
    }

    async function loadMessages(chatId) {
        const messages = await getMessagesByChatId(chatId);
        setMessages(messages);
    }

    async function addMessageButtonOnClick() {
        await addMessage(chat.id, appContext.user.id, text);
        setReload(!reload);
    }

    async function updateMessageButtonOnClick(messageId) {
        await updateMessage(messageId, text);
        setReload(!reload);
    }

    async function removeMessageButtonOnClick(messageId) {
        await removeMessageById(messageId);
        setReload(!reload);
    }
}
