// SocNetAngular/src/app/signin/signin.component.ts
import { Component } from '@angular/core';
import { AuthorizationService } from '../services/authorization.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './signin.component.html',
  styleUrl: './signin.component.css'
})
export class SigninComponent {
  email = '';
  password = '';
  constructor(private authorizationService: AuthorizationService) {}

  async signIn() {
    await this.authorizationService.signIn(this.email, this.password);
    window.location.href = '/profile';
  }
}

<section
    class="container"
>
    <input
        placeholder="Email"
        type="email"
        [(ngModel)]="email"
    />
    <input
        placeholder="Пароль"
        type="password"
        [(ngModel)]="password"
    />
    <button
        class="background-color-green"
        (click)="signIn()"
    >
        Войти
    </button>
</section>

// soc-net-react/src/routes/signin.js
import { useContext, useState } from "react";
import { signIn } from "../api/authenticationService";
import { AppContext } from "../contexts/contexts";
import { useNavigate } from "react-router-dom";
import './signin.css'

export default function Signin() {
    const appContext = useContext(AppContext);
    
    const navigate = useNavigate();
    
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    return (
        <section
            className="container"
        >
            <input
                placeholder="Email"
                type="email"
                onChange={e => setEmail(e.target.value)}
            />
            <input
                placeholder="Пароль"
                type="password"
                onChange={e => setPassword(e.target.value)}
            />
            <button
                className="background-color-green"
                onClick={signinButtonOnClick}
            >
                Войти
            </button>
        </section>
    );

    async function signinButtonOnClick() {
        const data = await signIn(email, password);
        appContext.setCookie('userId', data.id);
        appContext.setCookie('token', data.token);
        appContext.setIsAuthenticated(true);
        navigate('/');
    }
}
