// soc-net-react/src/routes/signup.js
import { useContext, useState } from "react";
import { signUp } from "../api/authenticationService";
import { AppContext } from "../contexts/contexts";
import { useNavigate } from "react-router-dom";
import './signup.css'

export default function Signup() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [birthDate, setBirthDate] = useState('');

    return (
        <section
            className="container"
        >
            <input
                placeholder="Email"
                type="email"
                onChange={e => setEmail(e.target.value)}
            />
            <input
                placeholder="Пароль"
                type="password"
                onChange={e => setPassword(e.target.value)}
            />
            <input
                placeholder="Имя"
                onChange={e => setFirstName(e.target.value)}
            />
            <input
                placeholder="Фамилия"
                onChange={e => setLastName(e.target.value)}
            />
            <input
                type="date"
                onChange={e => setBirthDate(e.target.value)}
            />
            <button
                className="background-color-green"
                onClick={signupButtonOnClick}
            >
                Зарегистрироваться
            </button>
        </section>
    );

    async function signupButtonOnClick() {
        const data = await signUp(email, password, firstName, lastName, birthDate);
        appContext.setCookie('userId', data.id);
        appContext.setCookie('token', data.token);
        appContext.setIsAuthenticated(true);
        navigate('/');
    }
}

// SocNetAngular/src/app/signup/signup.component.ts
import { Component } from '@angular/core';
import { AuthorizationService } from '../services/authorization.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css'
})
export class SignupComponent {
  email = '';
  password = '';
  firstName = '';
  lastName = '';
  birthDate = '';
  constructor(private authorizationService: AuthorizationService) {}

  async signUp() {
    await this.authorizationService.signUp(this.email, this.password, this.firstName, this.lastName, this.birthDate);
    window.location.href = '/profile';
  }
}

<section
    class="container"
>
    <input
        placeholder="Email"
        type="email"
        [(ngModel)]="email"
    />
    <input
        placeholder="Пароль"
        type="password"
        [(ngModel)]="password"
    />
    <input
        placeholder="Имя"
        [(ngModel)]="firstName"
    />
    <input
        placeholder="Фамилия"
        [(ngModel)]="lastName"
    />
    <input
        type="date"
        [(ngModel)]="birthDate"
    />
    <button
        class="background-color-green"
        (click)="signUp()"
    >
        Зарегистрироваться
    </button>
</section>
