// SocNetAngular/src/app/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';
import { NgIf } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [NgIf, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  @Input() isAuthenticated = false;
}

<header
    class="navigation-header"
>
    <nav
        class="navigation-menu"
    >
        <ul>
            <li>
                <a
                    class="menu-item"
                    routerLink="/users"
                    routerLinkActive="active"
                >
                    Пользователи
                </a>
            </li>
            @if (isAuthenticated) {
                <li>
                    <a
                        class="menu-item"
                        routerLink="/chats"
                        routerLinkActive="active"
                    >
                        Чаты
                    </a>
                </li>
                <li>
                    <a
                        class="menu-item"
                        routerLink="/profile"
                        routerLinkActive="active"
                    >
                        Профиль
                    </a>
                </li>
            }
            @else {
                <li>
                    <a
                        class="menu-item"
                        routerLink="/signup"
                        routerLinkActive="active"
                    >
                        Регистрация
                    </a>
                </li>
                <li>
                    <a
                        class="menu-item"
                        routerLink="/signin"
                        routerLinkActive="active"
                    >
                        Авторизация
                    </a>
                </li>
            }
        </ul>
    </nav>
</header>

// soc-net-react/src/components/navbar.js
import { Link, useLocation } from "react-router-dom";
import './navbar.css'

export default function Navbar({ isAuthenticated }) {
    const location = useLocation();

    return (
        <header
            className="navigation-header"
        >
            <nav
                className="navigation-menu"
            >
                <ul>
                    <li>
                        <Link
                            className={`menu-item ${location.pathname === '/users' ? 'active' : ''}`}
                            to={`/users`}
                        >
                            Пользователи
                        </Link>
                    </li>
                    { isAuthenticated ? (
                        <>
                            <li>
                                <Link
                                    className={`menu-item ${location.pathname.startsWith('/chats') ? 'active' : ''}`}
                                    to={`/chats`}
                                >
                                    Чаты
                                </Link>
                            </li>
                            <li>
                                <Link
                                    className={`menu-item ${location.pathname === '/profile' ? 'active' : ''}`}
                                    to={`/profile`}
                                >
                                    Профиль
                                </Link>
                            </li>
                        </>
                    ) : (
                        <>
                            <li>
                                <Link
                                    className={`menu-item ${location.pathname === '/signup' ? 'active' : ''}`}
                                    to={`/signup`}
                                >
                                    Регистрация
                                </Link>
                            </li>
                            <li>
                                <Link
                                    className={`menu-item ${location.pathname === '/signin' ? 'active' : ''}`}
                                    to={`/signin`}
                                >
                                    Авторизация
                                </Link>
                            </li>
                        </>
                    )}
                </ul>
            </nav>
        </header>
    );
}
