// soc-net-react/src/components/message.js
import './message.css'

export default function Message({ message, updateMessageButtonOnClick, removeMessageButtonOnClick }) {
    return (
        <section
            className="message-card"
        >
            <p
                className="message-text"
            >
                <strong>{message.user.firstName} {message.user.lastName}:</strong> {message.text}
            </p>
            <span
                className="message-time"
            >
                {message.dateTime.toString().replace('T', ' ').split('.')[0]}
            </span>
            <button
                className="background-color-green"
                onClick={() => updateMessageButtonOnClick(message.id)}
            >
                Изменить
            </button>
            <button
                className="background-color-red"
                onClick={() => removeMessageButtonOnClick(message.id)}
            >
                Удалить
            </button>
        </section>
    );
}

// SocNetAngular/src/app/message/message.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import Message from '../entities/message';

@Component({
  selector: 'app-message',
  standalone: true,
  imports: [],
  templateUrl: './message.component.html',
  styleUrl: './message.component.css'
})
export class MessageComponent {
  @Input() message = new Message;
  @Output() updateMessage = new EventEmitter();
  @Output() removeMessage = new EventEmitter();

  updateMessageOnClick() {
    this.updateMessage.emit();
  }

  removeMessageOnClick() {
    this.removeMessage.emit();
  }
}

<section
    class="message-card"
>
    <p
        class="message-text"
    >
        <strong>{{message.user.firstName}} {{message.user.lastName}}:</strong> {{message.text}}
    </p>
    <span
        class="message-time"
    >
        {{message.dateTime.toString().replace('T', ' ').split('.')[0]}}
    </span>
    <button
        class="background-color-green"
        (click)="updateMessageOnClick()"
    >
        Изменить
    </button>
    <button
        class="background-color-red"
        (click)="removeMessageOnClick()"
    >
        Удалить
    </button>
</section>
